GET http://127.0.0.1:5000/api/auth/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6InRhcm8iLCJlbWFpbCI6InRhcm9AdGVzdC5jb20iLCJpYXQiOjE2MjcwOTg5MTl9.gt_iM7WnfLdRT39nDMs8rL0iisyCNgdF32sclfkgKz4